<#import "parts/common.ftlh" as c>
<@c.page title="Main">
    <h1>${name}</h1>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium consequuntur dolorem maxime nemo non odio officiis possimus rem, sequi sunt temporibus ullam voluptas. Aperiam facere fuga hic porro vel.
    <div>
    <a href="/catalog">Catalog</a>
    <a href="/registration">registration</a>
    </div>
</@c.page>